name: Documentation

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install
        run: npm install
      - name: Deploy docs
        run: |
          git config --global user.name 'lalalune'
          git config --global user.email 'autonomousresearcher@gmail.com'
          git remote set-url origin 'https://lalalune:${{ secrets.GH_TOKEN }}@github.com/RubyResearch/agent-twitter-client.git'
          npm run docs:deploy
